name: format-check
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b  # v7.2.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      # basedpyright needs editable install to pick up builds
      - name: Install package and validate format + type-checking
        run: |
          uv pip install -e .
          uvx pre-commit run --all-files

      - name: Run package tests
        run: |
          uvx --with . pytest

      - name: Generate lockfile
        run: |
          ./scripts/generate-uv-lock.sh

      # Maximum retention period is 90 days
      - name: Save lockfile as build artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: uv.lock.${{ matrix.python-version }}
          path: uv.lock
          compression-level: 9

  cross-platform-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04-arm', 'windows-latest', 'macos-14']

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b  # v7.2.0

      - name: Run package tests
        run: |
          uvx --python 3.8 --isolated --with-editable . pytest
          uvx --python 3.9 --isolated --with-editable . pytest
          uvx --python 3.10 --isolated --with-editable . pytest
          uvx --python 3.11 --isolated --with-editable . pytest
          uvx --python 3.12 --isolated --with-editable . pytest
          uvx --python 3.13 --isolated --with-editable . pytest
          uvx --python 3.14 --isolated --with-editable . pytest
